name: Backend ECS

on:
  push:
    branches:
      - develop
      - main
      - "feature-*"
    paths:
      - "ecs/**"
      - "layer-root/python/**"
      - ".github/workflows/backend-ecs.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ecs/Dockerfile
          push: false  # Change to true once ECR login is set up
          tags: margana-puzzle-generator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
